### ISSUE TITLE
Bundled theme issues and patches must be submitted on Trac

### ISSUE THREAD

**Issue by carolinan** [WordPress/Default-theme-issue-tracker#4]
This repository is for collaborating on existing Trac tickets.

- New bundled theme issues must be [reported on Trac](https://core.trac.wordpress.org/newticket).
- File changes must not be submitted here, see the documentation for [submitting a patch](https://make.wordpress.org/core/handbook/tutorials/trac/submitting-a-patch/).

**Comment by karmatosed** [comment]
@carolinan for now I have added this to the readme file for the repo - hopefully this works over have it lost as issue. Is that good and are you ok with me closing this issue if that is the case?

**Comment by carolinan** [comment]
This issue is not actionable, I only pinned it here because the readme is not visible when one selects the Issues tab.
Can closed issues still be pinned?

**Comment by karmatosed** [comment]
@carolinan closed issue can still be pinned as far as I know yes.
