### ISSUE TITLE
Full height with short content approach

### ISSUE THREAD

**Issue by karmatosed** [WordPress/Default-theme-issue-tracker#8]
There is one issue so far reported for this but likely there might be more: https://core.trac.wordpress.org/ticket/50026

**Comment by karmatosed** [comment]
Interestingly I am not seeing more - are you  @sabernhardt and @carolinan?

**Comment by carolinan** [comment]
I think that it is so common for sites to display like that this people don't usually report it...

**Comment by karmatosed** [comment]
I am going to close it out from here as I can't find more than the report I saw.
